Add new node version
AWS dropped the support to old Node versions. When this lambda is
created, the following error is thrown:

* aws_lambda_function.function_noenv: Error creating Lambda function:
InvalidParameterValueException: The runtime parameter of nodejs6.10
is no longer supported for creating or updating AWS Lambda functions.
We recommend you use the new runtime (nodejs8.10) while creating
or updating functions.